name: monitoring
on:
  workflow_dispatch:
jobs:
  run-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install project
        run: pip install -r requirements.txt
      - name: Run health check
        run: python main.py
